version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: sh -c "npm run start"
    working_dir: /usr/app
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 15

  gateway:
    image: matheusprotzen/gateways-mock
    container_name: gateway
    ports:
      - 3001:3001
      - 3002:3002

volumes:
  db_data:
    driver: local
